### ISSUE TITLE
FATAL: failed to allocate device memory for long state

### ISSUE THREAD

**Issue by dinho-afsn** [xbbricker/ccminer-cryptonight-mac#1]
how to solve this error: FATAL: failed to allocate device memory for long state

**Comment by rizky** [comment]
Did you solve this problem?

**Comment by hugheba** [comment]
Same issue here. macOS 10.13.1, CUDA 9.0.222

**Comment by xbbricker** [comment]
I think this is due to an incompatibility with the CUDA 9 driver. Can you see if the issue is fixed by running [CUDA 8](https://www.nvidia.com/object/macosx-cuda-8.0.90-driver.html)?

**Comment by rizky** [comment]
Yes, It is solved by installing CUDA 8. Thanks @xbbricker!

**Comment by hugheba** [comment]
How did you downgrade from CUDA 9?
