### ISSUE TITLE
Driver does not support CUDA 5.5 API! Update your nVidia driver!

### ISSUE THREAD

**Issue by tomaszwojewoda** [xbbricker/ccminer-cryptonight-mac#4]
Hi there,
I am on High Sierra with working Nvidia Driver  378.10.10.10.25.102. When I go to run ccminer, I get an error: Driver does not support CUDA 5.5 API! Update your nVidia driver! Does anyone know where to go from here?
Tomasz

**Comment by xbbricker** [comment]
You need the CUDA driver in addition to the display driver. You can find links in the Setup section of the [Readme](https://github.com/xbbricker/ccminer-cryptonight-mac).

**Comment by fadattf** [comment]
I can confirm the error message.
I have installed the software as described in the setup section:
- CUDA 9.0 (9.0.176)
- Sierra 10.13.2 nvidea graphic cards drivers (378.10.10.10.25.102)

**Comment by FlyingTrashcan** [comment]
I have installed the CUDA drivers per the Readme and also get the CUDA 5.5 API error.  
 
CUDA 9.0.222
NVIDIA Web Driver 346.03.15f11
El Capitan 10.11.6.

**Comment by xbbricker** [comment]
I've confirmed this issue exists when running macOS 10.3.2, GPU driver 378.10.10.25.102 and CUDA driver 9.0.222. Please update to the 387.99 CUDA driver (see README for link). Also verify that the NVIDIA web driver is selected in the NVIDIA Driver Manager Preference Pane.
