### ISSUE TITLE
Other algo in original ccminer

### ISSUE THREAD

**Issue by amirjamez** [xbbricker/ccminer-cryptonight-mac#6]
Good job! 
I was wondering if you could make the original ccminer having all his `algo` as a binary as well. I could not get past the compilation issues on Mac OS Siera:

```
In file included from api.cpp:33:
./miner.h:152:21: error: use of undeclared identifier 'bswap_32'
        return (((uint64_t)bswap_32((uint32_t)((x)& 0xffffffffu)) << 32) | (uint64_t)bswap_32((uint32_t)((x) >> 32)));
                           ^
./miner.h:152:79: error: use of undeclared identifier 'bswap_32'
        return (((uint64_t)bswap_32((uint32_t)((x)& 0xffffffffu)) << 32) | (uint64_t)bswap_32((uint32_t)((x) >> 32)));

```

Thanks!

**Comment by tomaszwojewoda** [comment]
Yes, that would be super cool.

**Comment by xbbricker** [comment]
A quick google search turns up [rooi/ccminer_macos](https://github.com/rooi/ccminer_macos). If that doesn't work and there's still interest I could look into it.
