### ISSUE TITLE
Can't 'make' repo

### ISSUE THREAD

**Issue by Viskus** [xbbricker/ccminer-cryptonight-mac#8]
Hi,

I hope someone can help me here. I'm trying to compile the repo and when i use the 'make' command i get an error:
`/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in compat
Making all in jansson
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all-am'.
/usr/local/cuda/bin/nvcc -g -O2 -I . -D_FORCE_INLINES -I/usr/local/cuda/include -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50  -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 --maxrregcount=128 --ptxas-options=-v -I./compat/jansson -o cryptonight/cryptonight.o -c cryptonight/cryptonight.cu
nvcc fatal   : The version ('90100') of the host compiler ('Apple clang') is not supported
make[2]: *** [cryptonight/cryptonight.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
`

Can anyone assist? I have tried re-downloading the command line tools but nothing seems to work.

**Comment by xbbricker** [comment]
The Apple-supplied clang was likely too new for for your CUDA toolkit version. This kind of thing is unfortunately common with nvidia's tools.

For posterity, this comment may be of service
https://forums.developer.nvidia.com/t/macos-10-13-4-and-xcode-9-3-compatibility-broken-with-cuda-toolkit-9-1/60584/10
